-- =============================================================================
-- Dealer Communication Portal — PostgreSQL schema
-- =============================================================================
-- Target: PostgreSQL 14+ (Supabase uses 15+). Idempotent where practical; run with
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f database/02_schema.sql
--
-- Common columns on EVERY table (requested SQL Server style -> PostgreSQL):
--   Id         bigint PK                    -> id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   IsActive   bit default 1 not null       -> is_active   BOOLEAN     NOT NULL DEFAULT TRUE
--   CreatedBy  bigint                       -> created_by  BIGINT      (user id; nullable for system/import rows)
--   CreatedOn  datetime default getdate()   -> created_on  TIMESTAMPTZ NOT NULL DEFAULT now()
--   ModifiedBy bigint                       -> modified_by BIGINT
--   ModifiedOn datetime default getdate()   -> modified_on TIMESTAMPTZ NOT NULL DEFAULT now()
--                                              (+ trigger keeps it current on every UPDATE)
--
-- Conventions
--   * Everything lives in schema "dcp" (not "public"), so Supabase's auto-generated
--     Data API does not expose these tables by default.
--   * snake_case identifiers (PostgreSQL folds unquoted PascalCase to lower case).
--   * Soft delete = is_active = FALSE. Rows are never hard-deleted by the application.
--   * created_by / modified_by are audit values, intentionally NOT foreign keys
--     (avoids circular dependencies with users and allows system/import writes).
--   * Tenant isolation: business tables carry company_id; the API always filters by the
--     company of the authenticated user.
-- =============================================================================

BEGIN;

SET LOCAL client_min_messages = warning;  -- hide "does not exist, skipping" notices on re-runs

CREATE SCHEMA IF NOT EXISTS dcp;
SET search_path TO dcp, public;

-- Keeps modified_on current on every UPDATE.
CREATE OR REPLACE FUNCTION dcp.set_modified_on()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.modified_on := now();
    RETURN NEW;
END;
$$;

-- =============================================================================
-- 1. Lookup / reference tables
-- =============================================================================

CREATE TABLE IF NOT EXISTS dcp.roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by   BIGINT,
    created_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by  BIGINT,
    modified_on  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_roles_name UNIQUE (name)
);
COMMENT ON TABLE dcp.roles IS 'Application roles, e.g. Company Administrator.';

CREATE TABLE IF NOT EXISTS dcp.countries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    iso2_code    CHAR(2),
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by   BIGINT,
    created_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by  BIGINT,
    modified_on  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_countries_name UNIQUE (name),
    CONSTRAINT uq_countries_iso2 UNIQUE (iso2_code)
);

CREATE TABLE IF NOT EXISTS dcp.regions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50) NOT NULL,
    sort_order   SMALLINT    NOT NULL DEFAULT 0,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by   BIGINT,
    created_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by  BIGINT,
    modified_on  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_regions_name UNIQUE (name)
);
COMMENT ON TABLE dcp.regions IS 'Geographic zone within a country (North, South, East, West, Central).';

CREATE TABLE IF NOT EXISTS dcp.currencies (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         CHAR(3)      NOT NULL,
    name         VARCHAR(100) NOT NULL,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by   BIGINT,
    created_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by  BIGINT,
    modified_on  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_currencies_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS dcp.dealer_types (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50) NOT NULL,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by   BIGINT,
    created_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by  BIGINT,
    modified_on  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dealer_types_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS dcp.dealer_statuses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50) NOT NULL,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by   BIGINT,
    created_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by  BIGINT,
    modified_on  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dealer_statuses_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS dcp.communication_types (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50) NOT NULL,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by   BIGINT,
    created_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by  BIGINT,
    modified_on  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_communication_types_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS dcp.communication_statuses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50) NOT NULL,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by   BIGINT,
    created_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by  BIGINT,
    modified_on  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_communication_statuses_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS dcp.sectors (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(150) NOT NULL,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by   BIGINT,
    created_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by  BIGINT,
    modified_on  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_sectors_name UNIQUE (name)
);
COMMENT ON TABLE dcp.sectors IS 'Sector catalogue (source: sector.json).';

CREATE TABLE IF NOT EXISTS dcp.sub_sectors (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_id    BIGINT       NOT NULL REFERENCES dcp.sectors (id),
    name         VARCHAR(150) NOT NULL,
    sort_order   SMALLINT     NOT NULL DEFAULT 0,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by   BIGINT,
    created_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by  BIGINT,
    modified_on  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_sub_sectors_sector_name UNIQUE (sector_id, name)
);

-- =============================================================================
-- 2. Company, users and authentication
-- =============================================================================

CREATE TABLE IF NOT EXISTS dcp.companies (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_code         VARCHAR(30)  NOT NULL,
    name                 VARCHAR(200) NOT NULL,
    logo_text            VARCHAR(10),
    logo_url             VARCHAR(500),
    industry             VARCHAR(150),
    sector_id            BIGINT REFERENCES dcp.sectors (id),
    website              VARCHAR(300),
    email                VARCHAR(254),
    phone                VARCHAR(50),
    address_line1        VARCHAR(300),
    city                 VARCHAR(100),
    state                VARCHAR(100),
    postal_code          VARCHAR(20),
    country_id           BIGINT REFERENCES dcp.countries (id),
    region_id            BIGINT REFERENCES dcp.regions (id),
    registration_number  VARCHAR(100),
    tax_id               VARCHAR(100),
    employee_count       INTEGER CHECK (employee_count IS NULL OR employee_count >= 0),
    founded_year         SMALLINT CHECK (founded_year IS NULL OR founded_year BETWEEN 1800 AND 2200),
    is_active            BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by           BIGINT,
    created_on           TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by          BIGINT,
    modified_on          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_companies_code UNIQUE (company_code)
);
COMMENT ON COLUMN dcp.companies.sector_id IS 'Scopes the Sector / Sub-sector dealer filters.';

CREATE TABLE IF NOT EXISTS dcp.users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           BIGINT       NOT NULL REFERENCES dcp.companies (id),
    role_id              BIGINT       NOT NULL REFERENCES dcp.roles (id),
    user_code            VARCHAR(30)  NOT NULL,
    full_name            VARCHAR(150) NOT NULL,
    email                VARCHAR(254) NOT NULL,
    password_hash        VARCHAR(255),
    job_title            VARCHAR(100),
    phone                VARCHAR(50),
    country_id           BIGINT REFERENCES dcp.countries (id),
    region_id            BIGINT REFERENCES dcp.regions (id),
    last_login_on        TIMESTAMPTZ,
    failed_login_count   INTEGER NOT NULL DEFAULT 0,
    locked_until         TIMESTAMPTZ,
    is_active            BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by           BIGINT,
    created_on           TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by          BIGINT,
    modified_on          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_code UNIQUE (user_code)
);
COMMENT ON COLUMN dcp.users.password_hash IS 'Argon2id hash. NULL = no password set yet (invite pending).';
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email_lower ON dcp.users (lower(email));
CREATE INDEX IF NOT EXISTS ix_users_company ON dcp.users (company_id);

CREATE TABLE IF NOT EXISTS dcp.user_settings (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   BIGINT      NOT NULL REFERENCES dcp.users (id),
    default_page_size         SMALLINT    NOT NULL DEFAULT 20 CHECK (default_page_size IN (10, 20, 50)),
    apply_filters_instantly   BOOLEAN     NOT NULL DEFAULT TRUE,
    desktop_dealer_view       VARCHAR(10) NOT NULL DEFAULT 'table' CHECK (desktop_dealer_view IN ('table', 'cards')),
    is_active                 BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by                BIGINT,
    created_on                TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by               BIGINT,
    modified_on               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_settings_user UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS dcp.user_sessions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT       NOT NULL REFERENCES dcp.users (id),
    refresh_token_hash   VARCHAR(128) NOT NULL,
    remember_me          BOOLEAN      NOT NULL DEFAULT FALSE,
    expires_on           TIMESTAMPTZ  NOT NULL,
    revoked_on           TIMESTAMPTZ,
    user_agent           VARCHAR(500),
    ip_address           INET,
    is_active            BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by           BIGINT,
    created_on           TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by          BIGINT,
    modified_on          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_sessions_token UNIQUE (refresh_token_hash)
);
COMMENT ON TABLE dcp.user_sessions IS 'Refresh-token sessions (only a SHA-256 hash of the token is stored).';
CREATE INDEX IF NOT EXISTS ix_user_sessions_user ON dcp.user_sessions (user_id);

CREATE TABLE IF NOT EXISTS dcp.password_reset_tokens (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES dcp.users (id),
    token_hash    VARCHAR(128) NOT NULL,
    expires_on    TIMESTAMPTZ  NOT NULL,
    used_on       TIMESTAMPTZ,
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by    BIGINT,
    created_on    TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by   BIGINT,
    modified_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_password_reset_tokens_hash UNIQUE (token_hash)
);
CREATE INDEX IF NOT EXISTS ix_password_reset_tokens_user ON dcp.password_reset_tokens (user_id);

-- =============================================================================
-- 3. Dealers and products
-- =============================================================================

CREATE TABLE IF NOT EXISTS dcp.dealers (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                  BIGINT       NOT NULL REFERENCES dcp.companies (id),
    dealer_code                 VARCHAR(30)  NOT NULL,
    dealer_name                 VARCHAR(200) NOT NULL,
    legal_name                  VARCHAR(250),
    dealer_type_id              BIGINT       NOT NULL REFERENCES dcp.dealer_types (id),
    dealer_status_id            BIGINT       NOT NULL REFERENCES dcp.dealer_statuses (id),
    contact_person              VARCHAR(150),
    email                       VARCHAR(254),
    phone                       VARCHAR(50),
    website                     VARCHAR(300),
    registration_no             VARCHAR(100),
    full_address                VARCHAR(500),
    city                        VARCHAR(100),
    state                       VARCHAR(100),
    postal_code                 VARCHAR(20),
    country_id                  BIGINT       NOT NULL REFERENCES dcp.countries (id),
    region_id                   BIGINT       REFERENCES dcp.regions (id),
    sector_id                   BIGINT       REFERENCES dcp.sectors (id),
    last_transaction_date       DATE,
    last_transaction_amount     NUMERIC(18, 2),
    last_transaction_currency_id BIGINT      REFERENCES dcp.currencies (id),
    source_url                  VARCHAR(500),
    verification_date           DATE,
    is_demo                     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active                   BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by                  BIGINT,
    created_on                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by                 BIGINT,
    modified_on                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dealers_company_code UNIQUE (company_id, dealer_code)
);
COMMENT ON COLUMN dcp.dealers.dealer_code IS 'Public dealer id shown in the UI (e.g. DLR-1001); maps to dealer_id in dealers.json.';
COMMENT ON COLUMN dcp.dealers.legal_name IS 'Maps to company_name in dealers.json.';
COMMENT ON COLUMN dcp.dealers.is_demo IS 'TRUE for generated demo records.';
-- Filter / facet / sort support
CREATE INDEX IF NOT EXISTS ix_dealers_company_country_region ON dcp.dealers (company_id, country_id, region_id);
CREATE INDEX IF NOT EXISTS ix_dealers_company_status ON dcp.dealers (company_id, dealer_status_id);
CREATE INDEX IF NOT EXISTS ix_dealers_company_type ON dcp.dealers (company_id, dealer_type_id);
CREATE INDEX IF NOT EXISTS ix_dealers_company_sector ON dcp.dealers (company_id, sector_id);
CREATE INDEX IF NOT EXISTS ix_dealers_company_name ON dcp.dealers (company_id, lower(dealer_name));

CREATE TABLE IF NOT EXISTS dcp.products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200) NOT NULL,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by   BIGINT,
    created_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by  BIGINT,
    modified_on  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE dcp.products IS 'Product lines handled by dealers and sold in uploaded sales data.';
CREATE UNIQUE INDEX IF NOT EXISTS uq_products_name_lower ON dcp.products (lower(name));

CREATE TABLE IF NOT EXISTS dcp.product_sub_sectors (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT NOT NULL REFERENCES dcp.products (id),
    sub_sector_id  BIGINT NOT NULL REFERENCES dcp.sub_sectors (id),
    is_active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by     BIGINT,
    created_on     TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by    BIGINT,
    modified_on    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_product_sub_sectors UNIQUE (product_id, sub_sector_id)
);
COMMENT ON TABLE dcp.product_sub_sectors IS 'Which sub-sectors a product belongs to (powers the Sub-sector filter).';
CREATE INDEX IF NOT EXISTS ix_product_sub_sectors_sub_sector ON dcp.product_sub_sectors (sub_sector_id);

CREATE TABLE IF NOT EXISTS dcp.dealer_products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dealer_id    BIGINT   NOT NULL REFERENCES dcp.dealers (id),
    product_id   BIGINT   NOT NULL REFERENCES dcp.products (id),
    sort_order   SMALLINT NOT NULL DEFAULT 0,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by   BIGINT,
    created_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by  BIGINT,
    modified_on  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dealer_products UNIQUE (dealer_id, product_id)
);
CREATE INDEX IF NOT EXISTS ix_dealer_products_product ON dcp.dealer_products (product_id);

-- =============================================================================
-- 4. Communication
-- =============================================================================

CREATE TABLE IF NOT EXISTS dcp.communications (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                 BIGINT       NOT NULL REFERENCES dcp.companies (id),
    dealer_id                  BIGINT       NOT NULL REFERENCES dcp.dealers (id),
    communication_type_id      BIGINT       NOT NULL REFERENCES dcp.communication_types (id),
    communication_status_id    BIGINT       NOT NULL REFERENCES dcp.communication_statuses (id),
    direction                  VARCHAR(10)  NOT NULL CHECK (direction IN ('inbound', 'outbound')),
    sender_user_id             BIGINT       REFERENCES dcp.users (id),
    sender_name                VARCHAR(200) NOT NULL,
    recipient_name             VARCHAR(200) NOT NULL,
    recipient_email            VARCHAR(254),
    subject                    VARCHAR(200) NOT NULL,
    body                       TEXT,
    occurred_on                TIMESTAMPTZ  NOT NULL DEFAULT now(),
    is_active                  BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by                 BIGINT,
    created_on                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by                BIGINT,
    modified_on                TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE dcp.communications IS 'Messages, emails, calls and meetings with dealers (history + activity timeline).';
CREATE INDEX IF NOT EXISTS ix_communications_dealer_occurred ON dcp.communications (dealer_id, occurred_on DESC);
CREATE INDEX IF NOT EXISTS ix_communications_company_occurred ON dcp.communications (company_id, occurred_on DESC);

CREATE TABLE IF NOT EXISTS dcp.communication_attachments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    communication_id  BIGINT       NOT NULL REFERENCES dcp.communications (id),
    file_name         VARCHAR(255) NOT NULL,
    content_type      VARCHAR(150),
    size_bytes        BIGINT       NOT NULL CHECK (size_bytes >= 0 AND size_bytes <= 10485760),
    storage_path      VARCHAR(500) NOT NULL,
    is_active         BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by        BIGINT,
    created_on        TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by       BIGINT,
    modified_on       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_communication_attachments_communication ON dcp.communication_attachments (communication_id);

-- =============================================================================
-- 5. Sales uploads, records and exchange rates
-- =============================================================================

CREATE TABLE IF NOT EXISTS dcp.sales_uploads (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           BIGINT       NOT NULL REFERENCES dcp.companies (id),
    uploaded_by_user_id  BIGINT       NOT NULL REFERENCES dcp.users (id),
    file_name            VARCHAR(255) NOT NULL,
    original_file_name   VARCHAR(255),
    sheet_name           VARCHAR(100),
    content_type         VARCHAR(150),
    file_size_bytes      BIGINT       NOT NULL CHECK (file_size_bytes >= 0),
    file_sha256          CHAR(64),
    storage_backend      VARCHAR(20)  NOT NULL DEFAULT 'local',
    storage_path         VARCHAR(500),
    physical_path        VARCHAR(1000),
    status               VARCHAR(20)  NOT NULL DEFAULT 'processing'
                         CHECK (status IN ('processing', 'ready', 'failed')),
    total_rows           INTEGER      NOT NULL DEFAULT 0,
    valid_rows           INTEGER      NOT NULL DEFAULT 0,
    skipped_rows         INTEGER      NOT NULL DEFAULT 0,
    column_count         INTEGER      NOT NULL DEFAULT 0,
    column_mapping       JSONB,
    error_message        VARCHAR(1000),
    processed_on         TIMESTAMPTZ,
    is_active            BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by           BIGINT,
    created_on           TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by          BIGINT,
    modified_on          TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE dcp.sales_uploads IS 'Master row per uploaded sales workbook (detail: sales_upload_columns, sales_upload_rows, sales_records).';
COMMENT ON COLUMN dcp.sales_uploads.column_mapping IS 'Detected sheet header for each canonical column, e.g. {"customerName":"CustomerName"}.';
COMMENT ON COLUMN dcp.sales_uploads.file_name          IS 'Display name shown in the app.';
COMMENT ON COLUMN dcp.sales_uploads.original_file_name IS 'File name exactly as uploaded.';
COMMENT ON COLUMN dcp.sales_uploads.storage_path       IS 'Location inside the storage backend (relative key).';
COMMENT ON COLUMN dcp.sales_uploads.physical_path      IS 'Absolute path of the stored workbook on the API server when it was uploaded.';
COMMENT ON COLUMN dcp.sales_uploads.file_sha256        IS 'SHA-256 of the file content (integrity / duplicate detection).';
COMMENT ON COLUMN dcp.sales_uploads.sheet_name         IS 'Worksheet that was read (the first sheet).';
CREATE INDEX IF NOT EXISTS ix_sales_uploads_company_created ON dcp.sales_uploads (company_id, created_on DESC);

CREATE TABLE IF NOT EXISTS dcp.sales_upload_issues (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_upload_id   BIGINT        NOT NULL REFERENCES dcp.sales_uploads (id),
    row_number        INTEGER       NOT NULL,
    severity          VARCHAR(10)   NOT NULL DEFAULT 'warning' CHECK (severity IN ('warning', 'error')),
    message           VARCHAR(1000) NOT NULL,
    is_active         BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by        BIGINT,
    created_on        TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by       BIGINT,
    modified_on       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_sales_upload_issues_upload ON dcp.sales_upload_issues (sales_upload_id);

CREATE TABLE IF NOT EXISTS dcp.sales_records (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id        BIGINT         NOT NULL REFERENCES dcp.companies (id),
    sales_upload_id   BIGINT         NOT NULL REFERENCES dcp.sales_uploads (id),
    row_number        INTEGER        NOT NULL,
    customer_name     VARCHAR(250)   NOT NULL,
    dealer_id         BIGINT         REFERENCES dcp.dealers (id),
    country_name      VARCHAR(100)   NOT NULL,
    country_id        BIGINT         REFERENCES dcp.countries (id),
    location          VARCHAR(200),
    sales_year        SMALLINT       NOT NULL CHECK (sales_year BETWEEN 1900 AND 2200),
    sales_month       SMALLINT       NOT NULL CHECK (sales_month BETWEEN 1 AND 12),
    period_start      DATE           NOT NULL,
    product_name      VARCHAR(250)   NOT NULL,
    product_id        BIGINT         REFERENCES dcp.products (id),
    unit_of_measure   VARCHAR(30),
    quantity          NUMERIC(18, 4),
    amount            NUMERIC(18, 2) NOT NULL,
    currency_code     VARCHAR(10)    NOT NULL,
    currency_id       BIGINT         REFERENCES dcp.currencies (id),
    is_active         BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by        BIGINT,
    created_on        TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by       BIGINT,
    modified_on       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_sales_records_period CHECK (period_start = make_date(sales_year, sales_month, 1)),
    CONSTRAINT uq_sales_records_upload_row UNIQUE (sales_upload_id, row_number)
);
COMMENT ON TABLE dcp.sales_records IS 'Normalised rows of an uploaded sales workbook (Excel -> JSON -> rows).';
COMMENT ON COLUMN dcp.sales_records.dealer_id IS 'Resolved when customer_name matches a dealer of the company; otherwise NULL.';
CREATE INDEX IF NOT EXISTS ix_sales_records_company_period ON dcp.sales_records (company_id, period_start);
CREATE INDEX IF NOT EXISTS ix_sales_records_upload ON dcp.sales_records (sales_upload_id);
CREATE INDEX IF NOT EXISTS ix_sales_records_company_customer ON dcp.sales_records (company_id, customer_name);
CREATE INDEX IF NOT EXISTS ix_sales_records_company_product ON dcp.sales_records (company_id, product_name);

-- Detail 1: the sheet's columns (header, position, recognised field)
CREATE TABLE IF NOT EXISTS dcp.sales_upload_columns (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_upload_id  BIGINT       NOT NULL REFERENCES dcp.sales_uploads (id),
    column_index     SMALLINT     NOT NULL CHECK (column_index >= 1),
    column_letter    VARCHAR(3)   NOT NULL,
    header_name      VARCHAR(255) NOT NULL,
    data_key         VARCHAR(255) NOT NULL,
    mapped_field     VARCHAR(50),
    is_active        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by       BIGINT,
    created_on       TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by      BIGINT,
    modified_on      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_sales_upload_columns_index UNIQUE (sales_upload_id, column_index),
    CONSTRAINT uq_sales_upload_columns_key UNIQUE (sales_upload_id, data_key)
);
COMMENT ON TABLE dcp.sales_upload_columns IS 'Columns of an uploaded sales sheet, in sheet order.';
COMMENT ON COLUMN dcp.sales_upload_columns.column_index IS '1 = column A.';
COMMENT ON COLUMN dcp.sales_upload_columns.header_name IS 'Header text as it appears in row 1 ("" becomes "Column X").';
COMMENT ON COLUMN dcp.sales_upload_columns.data_key IS 'Unique key of this column inside dcp.sales_upload_rows.row_data.';
COMMENT ON COLUMN dcp.sales_upload_columns.mapped_field IS 'Recognised field (customerName, amount, ...) or NULL when the column is not used for analytics.';

-- Detail 2: every data row with all of its cells, valid or not
CREATE TABLE IF NOT EXISTS dcp.sales_upload_rows (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_upload_id  BIGINT      NOT NULL REFERENCES dcp.sales_uploads (id),
    row_number       INTEGER     NOT NULL CHECK (row_number >= 2),
    row_data         JSONB       NOT NULL,
    is_valid         BOOLEAN     NOT NULL,
    sales_record_id  BIGINT      REFERENCES dcp.sales_records (id),
    is_active        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by       BIGINT,
    created_on       TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by      BIGINT,
    modified_on      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_sales_upload_rows_row UNIQUE (sales_upload_id, row_number)
);
COMMENT ON TABLE dcp.sales_upload_rows IS 'Data rows of an uploaded sales sheet exactly as read (row 1 is the header).';
COMMENT ON COLUMN dcp.sales_upload_rows.row_number IS 'Excel row number (the first data row is 2).';
COMMENT ON COLUMN dcp.sales_upload_rows.row_data IS 'All cells keyed by dcp.sales_upload_columns.data_key, e.g. {"CustomerName": "...", "Amount": 468000}.';
COMMENT ON COLUMN dcp.sales_upload_rows.is_valid IS 'TRUE when the row became a dcp.sales_records row; see dcp.sales_upload_issues for why not.';
CREATE INDEX IF NOT EXISTS ix_sales_upload_rows_record ON dcp.sales_upload_rows (sales_record_id);

CREATE TABLE IF NOT EXISTS dcp.exchange_rates (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT         REFERENCES dcp.companies (id),
    currency_id      BIGINT         NOT NULL REFERENCES dcp.currencies (id),
    rate_to_usd      NUMERIC(18, 8) NOT NULL CHECK (rate_to_usd > 0),
    effective_date   DATE           NOT NULL,
    source           VARCHAR(200),
    is_active        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by       BIGINT,
    created_on       TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by      BIGINT,
    modified_on      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE dcp.exchange_rates IS 'USD value of 1 unit of a currency. company_id NULL = global default; set = company override.';
CREATE UNIQUE INDEX IF NOT EXISTS uq_exchange_rates_global
    ON dcp.exchange_rates (currency_id, effective_date) WHERE company_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_exchange_rates_company
    ON dcp.exchange_rates (company_id, currency_id, effective_date) WHERE company_id IS NOT NULL;

-- =============================================================================
-- 6. modified_on trigger on every table in the schema
-- =============================================================================

DO $$
DECLARE
    t record;
BEGIN
    FOR t IN
        SELECT c.table_name
        FROM information_schema.columns c
        JOIN information_schema.tables tb
          ON tb.table_schema = c.table_schema AND tb.table_name = c.table_name
        WHERE c.table_schema = 'dcp'
          AND c.column_name = 'modified_on'
          AND tb.table_type = 'BASE TABLE'
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_%1$s_modified_on ON dcp.%1$I', t.table_name);
        EXECUTE format(
            'CREATE TRIGGER trg_%1$s_modified_on BEFORE UPDATE ON dcp.%1$I '
            'FOR EACH ROW EXECUTE FUNCTION dcp.set_modified_on()',
            t.table_name
        );
    END LOOP;
END;
$$;

COMMIT;
