-- =============================================================================
-- Migration 0002 - Sales upload master/detail storage
-- =============================================================================
-- Master  : dcp.sales_uploads          one row per uploaded workbook: names, physical storage
--                                      location, checksum, sheet, counts (extended here)
-- Detail  : dcp.sales_upload_columns   one row per column of the sheet (header, position, mapping)
--           dcp.sales_upload_rows      one row per data row of the sheet with ALL its cells (JSONB),
--                                      valid or not, linked to the typed dcp.sales_records row
-- (dcp.sales_records keeps the typed, validated rows used by analytics; unchanged.)
--
-- Idempotent: safe to run on a database that already has these objects. Applied by Alembic
-- revision 0002_sales_upload_detail; database/02_schema.sql contains the same definitions.
-- =============================================================================

SET LOCAL client_min_messages = warning;

-- -----------------------------------------------------------------------------
-- Master: where and what the uploaded Excel file is
-- -----------------------------------------------------------------------------
ALTER TABLE dcp.sales_uploads
    ADD COLUMN IF NOT EXISTS original_file_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS sheet_name         VARCHAR(100),
    ADD COLUMN IF NOT EXISTS content_type       VARCHAR(150),
    ADD COLUMN IF NOT EXISTS file_sha256        CHAR(64),
    ADD COLUMN IF NOT EXISTS storage_backend    VARCHAR(20)  NOT NULL DEFAULT 'local',
    ADD COLUMN IF NOT EXISTS physical_path      VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS column_count       INTEGER      NOT NULL DEFAULT 0;

COMMENT ON COLUMN dcp.sales_uploads.file_name          IS 'Display name shown in the app.';
COMMENT ON COLUMN dcp.sales_uploads.original_file_name IS 'File name exactly as uploaded.';
COMMENT ON COLUMN dcp.sales_uploads.storage_path       IS 'Location inside the storage backend (relative key).';
COMMENT ON COLUMN dcp.sales_uploads.physical_path      IS 'Absolute path of the stored workbook on the API server when it was uploaded.';
COMMENT ON COLUMN dcp.sales_uploads.file_sha256        IS 'SHA-256 of the file content (integrity / duplicate detection).';
COMMENT ON COLUMN dcp.sales_uploads.sheet_name         IS 'Worksheet that was read (the first sheet).';

-- -----------------------------------------------------------------------------
-- Detail 1: the sheet's columns
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dcp.sales_upload_columns (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_upload_id  BIGINT       NOT NULL REFERENCES dcp.sales_uploads (id),
    column_index     SMALLINT     NOT NULL CHECK (column_index >= 1),
    column_letter    VARCHAR(3)   NOT NULL,
    header_name      VARCHAR(255) NOT NULL,
    data_key         VARCHAR(255) NOT NULL,
    mapped_field     VARCHAR(50),
    is_active        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by       BIGINT,
    created_on       TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by      BIGINT,
    modified_on      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_sales_upload_columns_index UNIQUE (sales_upload_id, column_index),
    CONSTRAINT uq_sales_upload_columns_key UNIQUE (sales_upload_id, data_key)
);
COMMENT ON TABLE dcp.sales_upload_columns IS 'Columns of an uploaded sales sheet, in sheet order.';
COMMENT ON COLUMN dcp.sales_upload_columns.column_index IS '1 = column A.';
COMMENT ON COLUMN dcp.sales_upload_columns.header_name IS 'Header text as it appears in row 1 ("" becomes "Column X").';
COMMENT ON COLUMN dcp.sales_upload_columns.data_key IS 'Unique key of this column inside dcp.sales_upload_rows.row_data.';
COMMENT ON COLUMN dcp.sales_upload_columns.mapped_field IS 'Recognised field (customerName, amount, ...) or NULL when the column is not used for analytics.';

-- -----------------------------------------------------------------------------
-- Detail 2: every data row with all of its cells
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dcp.sales_upload_rows (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_upload_id  BIGINT      NOT NULL REFERENCES dcp.sales_uploads (id),
    row_number       INTEGER     NOT NULL CHECK (row_number >= 2),
    row_data         JSONB       NOT NULL,
    is_valid         BOOLEAN     NOT NULL,
    sales_record_id  BIGINT      REFERENCES dcp.sales_records (id),
    is_active        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by       BIGINT,
    created_on       TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by      BIGINT,
    modified_on      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_sales_upload_rows_row UNIQUE (sales_upload_id, row_number)
);
COMMENT ON TABLE dcp.sales_upload_rows IS 'Data rows of an uploaded sales sheet exactly as read (row 1 is the header).';
COMMENT ON COLUMN dcp.sales_upload_rows.row_number IS 'Excel row number (the first data row is 2).';
COMMENT ON COLUMN dcp.sales_upload_rows.row_data IS 'All cells keyed by dcp.sales_upload_columns.data_key, e.g. {"CustomerName": "...", "Amount": 468000}.';
COMMENT ON COLUMN dcp.sales_upload_rows.is_valid IS 'TRUE when the row became a dcp.sales_records row; see dcp.sales_upload_issues for why not.';
CREATE INDEX IF NOT EXISTS ix_sales_upload_rows_record ON dcp.sales_upload_rows (sales_record_id);

-- -----------------------------------------------------------------------------
-- modified_on triggers for the new tables
-- -----------------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_sales_upload_columns_modified_on ON dcp.sales_upload_columns;
CREATE TRIGGER trg_sales_upload_columns_modified_on BEFORE UPDATE ON dcp.sales_upload_columns
    FOR EACH ROW EXECUTE FUNCTION dcp.set_modified_on();
DROP TRIGGER IF EXISTS trg_sales_upload_rows_modified_on ON dcp.sales_upload_rows;
CREATE TRIGGER trg_sales_upload_rows_modified_on BEFORE UPDATE ON dcp.sales_upload_rows
    FOR EACH ROW EXECUTE FUNCTION dcp.set_modified_on();
