-- =============================================================================
-- Migration 0006 - Regions per country, dealer sources, trade-channel dealer types
-- =============================================================================
-- * dcp.regions gets country_id: every country has its own regions. The unique key changes from
--   (name) to (country_id, name). Today's regions (North, South, East, West, Central) become India's;
--   India also gets "North East". For every other (country, region) pair used by a dealer, company
--   or user, that country gets its own region row with the same name and sort order, and the row is
--   repointed to it. Rows without a country keep the India region. Nothing is deleted.
-- * dcp.dealer_sources: every source a dealer was found in or confirmed by (crawler, registry, upload),
--   with the external id it has there (CIN, GSTIN, Udyam no., FSSAI licence no., ...). The single
--   dcp.dealers.source_url / verification_date stay as the primary source and latest confirmation.
-- * Dealer types for trade channels: Wholesaler, Retailer, Manufacturer, Exporter / Importer.
--
-- Idempotent: safe to run again and on a database created from the current 02_schema.sql.
-- Applied by Alembic revision 0006_regions_per_country.
-- =============================================================================

SET LOCAL client_min_messages = warning;

-- -----------------------------------------------------------------------------
-- Regions per country
-- -----------------------------------------------------------------------------
INSERT INTO dcp.countries (name, iso2_code) VALUES ('India', 'IN') ON CONFLICT DO NOTHING;

ALTER TABLE dcp.regions ADD COLUMN IF NOT EXISTS country_id BIGINT REFERENCES dcp.countries (id);

UPDATE dcp.regions
   SET country_id = (SELECT id FROM dcp.countries WHERE name = 'India')
 WHERE country_id IS NULL;

ALTER TABLE dcp.regions DROP CONSTRAINT IF EXISTS uq_regions_name;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_regions_country_name' AND conrelid = 'dcp.regions'::regclass
    ) THEN
        ALTER TABLE dcp.regions ADD CONSTRAINT uq_regions_country_name UNIQUE (country_id, name);
    END IF;
END $$;

-- Each country that uses a region of another country gets its own copy of that region.
INSERT INTO dcp.regions (country_id, name, sort_order)
SELECT DISTINCT used.country_id, r.name, r.sort_order
  FROM (SELECT country_id, region_id FROM dcp.dealers
        UNION SELECT country_id, region_id FROM dcp.companies
        UNION SELECT country_id, region_id FROM dcp.users) used
  JOIN dcp.regions r ON r.id = used.region_id
 WHERE used.country_id IS NOT NULL
   AND used.country_id <> r.country_id
ON CONFLICT DO NOTHING;

UPDATE dcp.dealers t
   SET region_id = own.id
  FROM dcp.regions used, dcp.regions own
 WHERE t.region_id = used.id
   AND used.country_id <> t.country_id
   AND own.country_id = t.country_id
   AND own.name = used.name;

UPDATE dcp.companies t
   SET region_id = own.id
  FROM dcp.regions used, dcp.regions own
 WHERE t.region_id = used.id
   AND t.country_id IS NOT NULL
   AND used.country_id <> t.country_id
   AND own.country_id = t.country_id
   AND own.name = used.name;

UPDATE dcp.users t
   SET region_id = own.id
  FROM dcp.regions used, dcp.regions own
 WHERE t.region_id = used.id
   AND t.country_id IS NOT NULL
   AND used.country_id <> t.country_id
   AND own.country_id = t.country_id
   AND own.name = used.name;

ALTER TABLE dcp.regions ALTER COLUMN country_id SET NOT NULL;

INSERT INTO dcp.regions (country_id, name, sort_order)
SELECT id, 'North East', 6 FROM dcp.countries WHERE name = 'India'
ON CONFLICT DO NOTHING;

COMMENT ON TABLE dcp.regions IS 'Geographic zone within a country (India: North, South, East, West, Central, North East).';
COMMENT ON COLUMN dcp.regions.country_id IS 'The country this region belongs to; region names are unique per country.';

-- -----------------------------------------------------------------------------
-- Trade-channel dealer types
-- -----------------------------------------------------------------------------
INSERT INTO dcp.dealer_types (name) VALUES
    ('Wholesaler'),
    ('Retailer'),
    ('Manufacturer'),
    ('Exporter / Importer')
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- Dealer sources
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dcp.dealer_sources (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dealer_id      BIGINT       NOT NULL REFERENCES dcp.dealers (id),
    source_url     VARCHAR(500) NOT NULL,
    source_kind    VARCHAR(30),
    source_name    VARCHAR(200),
    external_id    VARCHAR(100),
    first_seen_on  DATE         NOT NULL DEFAULT CURRENT_DATE,
    last_seen_on   DATE         NOT NULL DEFAULT CURRENT_DATE,
    evidence       JSONB,
    is_active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by     BIGINT,
    created_on     TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by    BIGINT,
    modified_on    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dealer_sources UNIQUE (dealer_id, source_url)
);
COMMENT ON TABLE dcp.dealer_sources IS
    'Every source a dealer was found in or confirmed by; dealers.source_url is the primary one.';
COMMENT ON COLUMN dcp.dealer_sources.source_kind IS
    'registry, msme_registry, tax_registry, food_licence, commodity_board, trade_fair, website, open_data, paid_api, upload, manual.';
COMMENT ON COLUMN dcp.dealer_sources.external_id IS 'The dealer''s id at the source: CIN, GSTIN, Udyam no., FSSAI licence no., ...';
COMMENT ON COLUMN dcp.dealer_sources.evidence IS 'Fields this source confirmed, e.g. {"phone": "+91 ...", "snippet": "..."}.';
CREATE INDEX IF NOT EXISTS ix_dealer_sources_external_id ON dcp.dealer_sources (external_id) WHERE external_id IS NOT NULL;

DROP TRIGGER IF EXISTS trg_dealer_sources_modified_on ON dcp.dealer_sources;
CREATE TRIGGER trg_dealer_sources_modified_on BEFORE UPDATE ON dcp.dealer_sources
    FOR EACH ROW EXECUTE FUNCTION dcp.set_modified_on();

-- Every dealer's current primary source becomes its first dealer_sources row.
INSERT INTO dcp.dealer_sources (dealer_id, source_url, source_kind, first_seen_on, last_seen_on)
SELECT d.id, d.source_url, 'upload',
       COALESCE(d.verification_date, d.created_on::date), COALESCE(d.verification_date, d.created_on::date)
  FROM dcp.dealers d
 WHERE d.source_url IS NOT NULL
ON CONFLICT DO NOTHING;
